### ISSUE TITLE
Can’t download reddit video use MG 1.1.7

### ISSUE THREAD

**Issue by incIined** [MediaGrabber/iOS-Workflow#10]
this specifically: https://v.redd.it/v6pkel05pjl31

gives me this: 
![6FB49535-50A8-438F-8AAC-3A7987E57708](https://user-images.githubusercontent.com/30244311/64589333-b7c1eb00-d359-11e9-9a92-76cdf960a258.png)

on an iPhone X on 12.4, Shortcuts v2.2.2

**Comment by sayem314** [comment]
Use the latest version (v1.3.5) from this repo (.shortcut file)

**Comment by incIined** [comment]
will do, couldn’t figure out how to update it. perhaps that should be added to the readme?

**Comment by incIined** [comment]
thank you, it worked.

**Comment by sayem314** [comment]
Open bianry file with "Open in shortcuts"
PR welcome!
