### ISSUE TITLE
What tool was used to generate .shortcut file from .txt?

### ISSUE THREAD

**Issue by stas-sl** [MediaGrabber/iOS-Workflow#11]
Hi!

Can you please, tell what tool did you use to generate .shortcut file from .txt? 

Thanks!

**Comment by atnbueno** [comment]
Older versions of iTunes had a command line tool (plistutil) that allowed conversion to/from binary/xml/json versions of a plist file (.shortcut files are binary plists)

It can also be done with JavaScript (node/bplist)

**Comment by sayem314** [comment]
I have used scpl

**Comment by stas-sl** [comment]
Thanks!
