### ISSUE TITLE
beta5 just saves a picture of the video filename, not the video itself

### ISSUE THREAD

**Issue by deanylev** [MediaGrabber/iOS-Workflow#12]
I've been using an older version for months now (not sure which one in particular) and got an alert to upgrade to beta5, so I did. Now when I try download a video, the list of resolutions appear, and I can save to camera roll, but bizarrely all that gets saved is a picture of the video filename. 

I am using an iPhone XS Max running iOS 13.6.1.
![image](https://user-images.githubusercontent.com/22049511/90862027-257eef80-e3d0-11ea-8a68-069830f2584a.png)

**Comment by sayem314** [comment]
Is this still an issue? Can you provide an example link and choosen format I should try on?

**Comment by deanylev** [comment]
I don't seem to be able to get it to happen anymore so I'll go ahead and close this :)
