### ISSUE TITLE
2.0 beta 5 fails to save video in Camera Roll - PHPotosErrorDomain error-1

### ISSUE THREAD

**Issue by Rikfc** [MediaGrabber/iOS-Workflow#13]
Hi, when Media Grabber tries to save video to camera roll, appears this pop up error. I have latest iOS 13 release
![IMG_0947](https://user-images.githubusercontent.com/44293391/91382199-75731180-e829-11ea-99f7-f4de70095355.jpeg)

**Comment by sayem314** [comment]
How often does this happen? Does a system restart fix it? Is it specific for any sites?

**Comment by Rikfc** [comment]
I did other tests and found that the problem is related only to PornHub.

**Comment by Rikfc** [comment]
I downloaded beta 6 and tested it on various sites. Everything seems to work correctly and at the end the popup appears indicating that the video has been saved on the camera roll. In reality, however, the video is not on the roll and therefore is not saved anywhere

**Comment by sayem314** [comment]
Was it `webm` container? Camera Roll cannot save `webm`.

**Comment by Rikfc** [comment]
I don't know what format it is but they are websites on
which worked before. It doesn't even work on Youtube. I also tried rebooting
