### ISSUE TITLE
beta 5.0 Video Youtube Download Error.

### ISSUE THREAD

**Issue by bonxz** [MediaGrabber/iOS-Workflow#14]
![IMG_4910](https://user-images.githubusercontent.com/61289944/92301693-f044d680-ef65-11ea-9a4b-85c097963161.jpeg)

**Comment by sayem314** [comment]
This is caused by the youtube rate-limit. Thousands of people use MG everyday and hence this happens a lot. I'm working on a method to decrypt videos locally to avoid this in the future version.

**Comment by sayem314** [comment]
Fixed on beta 6
