### ISSUE TITLE
Instagram again

### ISSUE THREAD

**Issue by dabepp** [MediaGrabber/iOS-Workflow#19]
I get this error recently:
![7220DF3B-0AC2-4EAB-B8B5-E8094C3C2985](https://user-images.githubusercontent.com/28548283/109026231-d2a82c80-76bf-11eb-9178-b3bdc71d8c51.jpeg)

i can select the resolution or audio only then the progress-circle shows and then this. 

This was the media I wanted to grab:

https://www.reddit.com/r/JusticeServed/comments/lqw75q/basically_suicide/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by sayem314** [comment]
The Reddit issue has been fixed now but not sure why did you put Instagram in the title.

**Comment by dabepp** [comment]
> The Reddit issue has been fixed now but not sure why did you put Instagram in the title.

My bad! Tbh: I don't know why! :D Thank you!
