### ISSUE TITLE
Slow downloads

### ISSUE THREAD

**Issue by Rikfc** [MediaGrabber/iOS-Workflow#3]
Compared to the version 1.3.1, downloads are so slower and are not completed. I tried to restore old version but the pop-up forces me to install the new release. I've tried in iPhone ad iPad

**Comment by sayem314** [comment]
First, v1.3.2 did not changed any downloads action but fixed extractor problem.

Second, download speed does not have anything to do with shortcuts here, it depends on your network and upstream.

**Comment by Rikfc** [comment]
I know, it's strange, but with the previous version I had no problems. My network works well (I did speedtest) and then downloading the same video through a 3rd party app (like Amerigo or Total Downloader), the download is very fast...

**Comment by Rikfc** [comment]
Sorry if I insist, but I think the problem is related to some famous adult sites.
In fact, on the other sites the download speed is high.
Probably these sites have a system to voluntarily reduce the download speed.
It would be interesting to understand how to solve the problem. Maybe using multiple connections ..?

**Comment by sayem314** [comment]
Yes most well-known sites throttle connection speed, we might be able to improve speed on our standalone app in the future. But on shortcuts we really can’t fix this as the downloads function cannot be modified.
