### ISSUE TITLE
Could you add support for v.redd.it videos?

### ISSUE THREAD

**Issue by snorbaard** [MediaGrabber/iOS-Workflow#5]
When trying to download videos from v.redd.it, they seem to fail.

From within an app (Antenna), sharing the media link to MediaGrabber fails with

> **Internal Server Error**
> ERROR requested format not available
> 
> Query: https://v.redd.it/xql8v4ylekl21

When sending the link to MediaGrabber from Safari, the error message is:

> **Internal Server Error**
> ERROR: requested format not available
> 
> Query: 
> https://www.reddit.com/r/WTF/comments/azzp3n/when_its_not_quite_your_time/

Thanks!

**Comment by sayem314** [comment]
I’m aware of that. Recently I have moved Media Grabber servers to a new VPS. Need to install some more stuff like ffmpeg on server. Will fix it soon!

v.reddit.it link support will be added as well 🙂

**Comment by sayem314** [comment]
Update: Reddit issue has been fixed.

**Comment by sayem314** [comment]
Update 2: v.redd.it is now supported :)

**Comment by snorbaard** [comment]
That's awesome! Will test and provide feedback.

**Comment by snorbaard** [comment]
Works like a charm! 
Thank you!
