### ISSUE TITLE
Reddit video quality really low?

### ISSUE THREAD

**Issue by atom097** [MediaGrabber/iOS-Workflow#6]
Hello,

Downloading videos from reddit seems to save very low quality, blurry videos. Is there any way to set the quality to always maximum? I tried browsing the shortcut steps and couldn’t find an entry pertaining to reddit video quality.

Thank you.

**Comment by sayem314** [comment]
Yes it’s set to download lowest quality. No, there is no way to change this atm.

**Comment by sayem314** [comment]
This has been fixed.

**Comment by avnibu** [comment]
This issue appears to have revived. As of writing this comment, only low quality option is available for reddit videos.
