### ISSUE TITLE
Some downloaded videos seem to be "broken" or unsupported by WhatsApp

### ISSUE THREAD

**Issue by snorbaard** [MediaGrabber/iOS-Workflow#7]
I know this is asking about compatibility with an app that you have no control over, but a rather large number of videos I download via Media Grabber (usually Gifs from v.redd.it) seem to be unsupported by Whatsapp. 
While the downlded videos play fine in Preview, when they're sent on to Whatsapp, the message "Couldnt send message. Try again or open Whatsapp to resend"

Neither option works. 
It appears that the video that is created is somehow incompatible with Whatsapp. A workaround is to send it through recompression which sometimes works, but it ends up with a vastly inferior video. 

I don't know enough about the backend to know if what type of video is being created that's incompatible with Whatsapp. Is this something you could investigate at all?
![D59B6614-E70E-485E-BF5E-138830B407FA](https://user-images.githubusercontent.com/7551208/57235190-a1f68f00-7022-11e9-9350-49ce85cc9130.jpeg)

Example URL: https://www.reddit.com/r/StartledCats/comments/bkxeue/no_no_touchy_tha_toes/

**Comment by sayem314** [comment]
I have no control over reddit hosted gifs. I have done a passthrough conversation inside Media Grabber and the quality is fine. Using the built-in “Convert videos...” option is your best bet atm.
