### ISSUE TITLE
Youtube API update breaks Youtube downloading

### ISSUE THREAD

**Issue by ghost** [MediaGrabber/iOS-Workflow#9]
Due to Youtube's new api quota update (https://developers.google.com/youtube/v3/getting-started#quota) downloading Youtube videos for free is almost impossible unless you do it right when the quota resets. The error message can be found below:

![Error message](https://user-images.githubusercontent.com/28767742/61331939-ff604680-a7f0-11e9-8372-0fc4e0cada35.jpeg)

**Comment by sayem314** [comment]
I'm aware of that. With the release of iOS 13 (stable), I'm planning to re-write the backend and shortcuts from scratch with smart algorithms that could fix it hopefully!

**Comment by ghost** [comment]
Awesome, thanks dude.

**Comment by goggler91** [comment]
Thanks, was going to post this issue. Great to hear you're looking to update it with under the hood improvements for iOS 13

**Comment by sayem314** [comment]
This has been fixed with latest server side patch. Follow #8 for further discussion and beta updates of MG!
